GET http://localhost:4001/api/workers/inventory
###


GET http://localhost:4000/api/inventory

###

POST http://localhost:4000/api/inventory
Content-Type: application/json

{
    "name": "normal bicycle",
    "locations": [
        {
            "location": "Oulu", 
            "amount": 4000
        }
    ]
}

###


GET http://localhost:5001/api/orders