
GET http://localhost:4000/api/products

###

POST http://localhost:4000/api/products
Content-Type: application/json

{
    "name": "normal bicycle",
    "locations": [
        {
            "location": "Oulu", 
            "amount": 140
        }
    ]
}

###


GET http://localhost:5001/api/orders